(()=>{
const projects={
museum:{no:'01',title:'Музей<br>о море',type:'Музейное освещение',year:'2026',image:'../img/museum/cover.webp',imageAlt:'Корабль в тумане — обложка проекта «Музей о море»',lead:'Световая концепция экспозиции',body:'Световая драматургия ведёт посетителя от открытого горизонта к глубине подводного мира.',role:'Концепция / световой сценарий',status:'Дипломный проект',next:'kresty.html',nextTitle:'Кресты',gallery:[],zones:[
 {title:'Входная группа',caption:'Динамическая каустика',description:'Изогнутые металлические пластины на потолке и узкий направленный луч создают на полу динамическое переотражение света.',image:'../img/museum/zone-01-graphic.png',alt:'Входная группа музея с динамической каустикой на полу'},
 {title:'Ресепшен',caption:'Ориентация',description:'Зона встречи и навигации задаёт направление дальнейшего движения по экспозиции.',image:'../img/museum/zone-02-graphic.png',alt:'Ресепшен музея с холодной синей подсветкой'},
 {title:'Маяк',caption:'Открытый горизонт',description:'Медиаэкран и направленный луч собирают пространство вокруг образа маяка.',image:'../img/museum/zone-03-graphic.png',alt:'Интерактивный зал с панорамой моря и маяком'},
 {title:'Парус',caption:'Ветер и движение',description:'Свет выявляет полупрозрачность паруса и превращает его в главный ориентир пространства.',image:'../img/museum/zone-04-graphic.png',alt:'Экспозиционный зал с парусом и световыми лучами'},
 {title:'Паровой мотор',caption:'Энергия движения',description:'Контрастные направленные лучи выявляют механизм и подчёркивают техногенный характер пространства.',image:'../img/museum/zone-05-graphic.png',alt:'Техногенный зал с паровым мотором и световыми проекциями'},
 {title:'Рубка «Литке»',caption:'Управление светом',description:'Тёплые направленные лучи связывают элементы рубки и подчёркивают тактильность экспонатов.',image:'../img/museum/zone-06-graphic.png',alt:'Инсталляция рубки Литке с рулевыми колёсами'},
 {title:'Подлодка',caption:'Давление глубины',description:'Синий свет и масштабная графика создают атмосферу погружения и физическое ощущение давления воды.',image:'../img/museum/zone-07-graphic.png',alt:'Зал Подлодка с эффектом погружения под воду'},
 {title:'Атом',caption:'Лёд и холод',description:'Каустика на левой стене напоминает движение льда, а нависающий над посетителем объём атомохода усиливает ощущение холода и давления.',image:'../img/museum/zone-08-graphic.png',alt:'Зал Атом с нависающим объёмом атомохода и ледяной каустикой'}
]},
kresty:{no:'02',title:'Кресты',type:'Архитектурный свет',year:'2026',image:'../img/kresty-cover.jpg',imageAlt:'Обложка презентации «Тени прошлого. Тюрьма Кресты»',lead:'Световой мастер-план исторического комплекса строится от городского силуэта к архитектурной детали и масштабу человека.',body:'Полная презентация проекта собрана ниже единым блоком: исследование места, концепция, световые сценарии и проектные решения.',role:'Анализ / мастер-план / концепция',status:'Полная презентация / 41 слайд',next:'system-coordinates.html',nextTitle:'Система координат',slides:Array.from({length:41},(_,i)=>`../img/kresty-slides/slide-${String(i+1).padStart(2,'0')}.jpg`),slidesAlt:'Кресты',gallery:[]},
'system-coordinates':{no:'03',title:'Система<br>координат',type:'Конкурс муралов',year:'Эскиз',image:'../img/system-coordinates-cover.jpg',imageAlt:'Обложка презентации «Система координат. Сахалина»',lead:'Конкурсная работа для дома на улице Космонавта Поповича, 67 на Сахалине.',body:'Визуальная система соединяет координаты места, образы моря, гор и света маяка. Ниже представлена авторская презентация целиком.',role:'Идея / эскиз',status:'Полная презентация',next:'clausura.html',nextTitle:'Клаузура',slides:['../img/system-coordinates/slide-01.jpg','../img/system-coordinates/slide-02.jpg','../img/system-coordinates/slide-03.jpg','../img/system-coordinates/slide-04.jpg','../img/system-coordinates/slide-05.jpg'],pdf:'../docs/system-coordinates.pdf',gallery:[]},
clausura:{no:'04',title:'Клаузура',type:'Световые объекты',year:'Конкурс',image:'../img/clausura/sukharev-visual.jpg',imageAlt:'Объект «Сухаревская башня»',lead:'Два объекта исследуют память города как нематериальный слой, который можно проявить светом.',body:'«Сухаревская башня» возвращает утраченную архитектуру через тень почти невидимой конструкции. «Москва. Слои времени» соединяет старую и современную карты в одной световой проекции.',role:'Идея / световой объект / визуализация',status:'Конкурсная работа',next:'theatre.html',nextTitle:'Театр отсутствия',gallery:[],featuredWorks:[
 {no:'01',title:'Сухаревская башня',image:'../img/clausura/sukharev-visual.jpg',crop:'sukharev',idea:'Мне хотелось построить пространство, где архитектура существует не из камня, а из света. Башня собрана из почти невидимых лесок — тонких линий воздуха. Когда на них падает луч, появляется её тень, будто память формы, которая больше не принадлежит реальности. Это про присутствие в отсутствии, про то, как свет может вернуть то, чего уже нет.',meaning:'Для меня это проект о памяти и хрупкости. Всё исчезает, но остаётся нематериальный, световой след. Башня существует только пока есть свет и внимание зрителя — так прошлое удерживается через взгляд и желание помнить.',materials:'Стекло, леска, алюминий, текстиль, направленный тёплый свет.'},
 {no:'02',title:'Москва. Слои времени',image:'../img/clausura/moscow-visual.jpg',crop:'moscow',idea:'Я соединила две карты — старую и новую. Старая лежит под стеклом как сохранённый слой города, а новая появляется светом сверху, выходит за рамки и продолжается на полу. Проекция не стирает старое, а показывает, как город растёт и нарастает на самого себя.',meaning:'Это работа о времени и движении. Город — живой организм, и мы видим только его текущий слой. Когда старое и новое совпадают, возникает ощущение пульса — будто прошлое и настоящее дышат вместе.',materials:'Инсталляция, печатная карта, стекло, проектор, свет.'}
 ]},
theatre:{no:'05',title:'Театр<br>отсутствия',type:'Музей Вадима Сидура',year:'Реализация',image:'../img/sidur/image7.jpeg',imageAlt:'Концептуальный эскиз светового решения для Музея Вадима Сидура',lead:'Световая концепция выставки «Театр отсутствия» и новой постоянной экспозиции «Вадим Сидур. Карта мифа».',body:'Свет становится инструментом экспозиционной драматургии: выделяет произведения, формирует тени и направляет движение зрителя, одновременно учитывая требования к сохранности экспонатов.',role:'Световая концепция / подбор оборудования / реализация',status:'Реализованный проект',author:'Оксана Никитина / Анна Золотилина',next:'vdnh.html',nextTitle:'Павильон №49',gallery:[],sidurCase:{sketches:['../img/sidur/image1.png','../img/sidur/image2.jpg','../img/sidur/image3.jpg','../img/sidur/image4.jpg','../img/sidur/image5.jpeg','../img/sidur/image7.jpeg'],photos:['../img/sidur/exhibition-06.jpg','../img/sidur/exhibition-01.jpg','../img/sidur/exhibition-02.jpg','../img/sidur/exhibition-03.jpg','../img/sidur/exhibition-04.jpg','../img/sidur/exhibition-05.jpg']}},
vdnh:{no:'06',title:'Павильон<br>№49',type:'ВДНХ',year:'Выставка',image:'../img/vdnh/photo-01.jpg',imageAlt:'Выставочный проект в павильоне №49 на ВДНХ',lead:'Самостоятельный выставочный проект в павильоне №49 на ВДНХ.',body:'В проекте свет работает вместе с отражающими материалами, графикой и объектами экспозиции, выделяя отдельные сценарии внутри насыщенного выставочного пространства.',role:'Участие в выставочном проекте',status:'Реализация',next:'velikaya.html',nextTitle:'Великая',gallery:['../img/vdnh/photo-01.jpg','../img/vdnh/photo-02.jpg','../img/vdnh/photo-03.jpg','../img/vdnh/photo-04.jpg','../img/vdnh/photo-05.jpg']},
velikaya:{no:'07',title:'Великая',type:'Русский музей',year:'Выставка',image:'../img/velikaya/photo-01.jpg',imageAlt:'Экспозиция выставки «Великая»',lead:'Выставочный проект Русского музея — отдельный кейс в портфолио.',body:'Фотографии показывают итоговую экспозицию и работу света с живописью, витринами и архитектурой залов.',role:'Монтаж экспозиции',status:'Реализация',next:'cloud.html',nextTitle:'Облако',gallery:['../img/velikaya/photo-01.jpg','../img/velikaya/photo-02.jpg']},
cloud:{no:'08',title:'Облако',type:'Световая медиаинсталляция',year:'Исследование / 2026',image:'../img/cloud/projector-waves.png',imageAlt:'Подвесная гранёная инсталляция «Облако» с проекцией и внутренним светом',lead:'Облако исследует границу между поверхностью и внутренним световым объёмом. Его оболочка собрана из зеркальных и прозрачных треугольных граней.',body:'Один лазер входит через прозрачную панель и многократно отражается от рассчитанной последовательности зеркальных граней. Все панели, не участвующие в маршруте луча, остаются прозрачными. Второй световой слой создаёт проектор: изображение ложится на наружные грани, а через стекло частично проникает внутрь и проявляет глубину объекта. Представленные кадры фиксируют три направления разработки и сценарий видеомэппинга; финальная юстировка выполняется на физическом прототипе.',role:'Автор / концепция / световая и оптическая схема',status:'В разработке',next:'museum.html',nextTitle:'Музей о Море',gallery:['../img/cloud/projector-waves.png','../img/cloud/cold-spectrum.png','../img/cloud/optical-core.png','../img/cloud/prismatic.png','../img/cloud/projector-clouds.png','../img/cloud/facet-trace.png']},
objects:{no:'07',title:'Объекты<br>света',type:'Серия исследований',year:'01—09',image:'../img/obj-prizma-pair.png',imageAlt:'Серия экспериментальных световых объектов',lead:'Девять учебных экспериментов с преломлением, рассеиванием, цветом, отражением, материалом и формой.',body:'Серия показывает свет не как оформление, а как физический материал. Каждый объект изолирует один принцип и проверяет, как он влияет на образ, поверхность и окружающее пространство.',role:'Исследование / прототипирование',status:'Серия объектов',next:'museum.html',nextTitle:'Музей о Море',gallery:['../img/obj-prizma.png','../img/obj-prizma-pair.png','../img/obj-diffuz.png','../img/obj-perforacia.png','../img/obj-organika.png','../img/obj-oblako.png','../img/obj-smeshenie.png','../img/obj-avtoportret.png','../img/obj-bra.png']}
};
const project=projects[document.body.dataset.project];
if(project){
 document.title=`${project.title.replace('<br>',' ')} — Оксана Никитина`;
 if(document.body.dataset.project==='cloud'){
  document.querySelector('#content').innerHTML=`<article class="cloud-case"><section class="cloud-cover"><img src="${project.image}" alt="${project.imageAlt}"><div class="cloud-cover__meta"><span>Световая медиаинсталляция</span><h1>Облако</h1></div></section><section class="project-story section"><h2>О проекте</h2><div class="project-story__copy"><p>«Облако» — размышление о том, как сделать невесомый материал — свет — ощутимым и почти телесным, сохранив ощущение лёгкости.</p><p>Объект не изображает облако буквально. Его объём возникает из прозрачной оболочки, бликов и светового маршрута внутри: зритель видит не массивную форму, а свет, который на мгновение собирает её из воздуха.</p></div></section><section class="cloud-model section" aria-labelledby="cloud-model-title"><div class="cloud-model__head"><span>Интерактивная 3D-модель</span><h2 id="cloud-model-title">Конструкция<br>и свет</h2><p>Зажмите модель мышью или пальцем и поверните её. Серебряные треугольники обозначают зеркальные поверхности, прозрачные — стеклянную оболочку.</p></div><div class="cloud-technical"><p class="cloud-technical__lead">Инсталляция собрана как лёгкий пространственный каркас из повторяющихся треугольных модулей. Часть модулей получает зеркальное покрытие, остальные остаются прозрачными и сохраняют визуальную проницаемость объекта.</p><dl><div><dt>Каркас</dt><dd>Жёсткая алюминиевая сетка удерживает геометрию и позволяет заменять отдельные панели без разборки всего объёма.</dd></div><div><dt>Оптический маршрут</dt><dd>Лазер входит через прозрачную грань. Зеркальные панели разворачивают его внутри объекта; грани вне маршрута остаются стеклянными.</dd></div><div><dt>Наружный слой</dt><dd>Проектор работает по внешней оболочке: изображение дробится по граням, а часть света проходит внутрь и проявляет глубину.</dd></div><div><dt>Настройка</dt><dd>Углы зеркал и положение источника юстируются на прототипе. При смещении прибора меняется последовательность отражений, поэтому маршрут пересчитывается и настраивается заново.</dd></div></dl></div><div class="cloud-viewer" data-cloud-viewer data-model="../models/cloud-optics.json"><canvas aria-label="Интерактивная трёхмерная модель инсталляции Облако"></canvas><div class="cloud-viewer__hud"><span>Зажмите и вращайте модель</span><button type="button" data-cloud-reset>Сбросить вид</button></div><div class="cloud-viewer__status" data-cloud-status>Загрузка модели…</div></div></section><a class="next-project" href="${project.next}"><span>Следующий проект<strong>${project.nextTitle}</strong></span><i>↗</i></a></article>`;
  return;
 }
 if(document.body.dataset.project==='museum'){
  const museumText=[
   'Музей о море построен как последовательность состояний морской среды, раскрывающих её характер через пространство, экспозицию, свет и мультимедиа. В основе проекта лежит идея погружения: посетитель проходит путь от первого ощущения ветра, наполняющего парус, и открытого горизонта до глубины подводного мира, где свет становится редким ориентиром, а пространство приобретает плотность, тишину и ощущение глубины.',
   'Как светодизайнер, в этом проекте я рассматриваю свет как главный инструмент пространственной драматургии. Свет не только выявляет архитектуру и экспозицию, но и направляет движение посетителя, меняет восприятие пространства и сопровождает переходы между состояниями моря. Благодаря изменению интенсивности, направления, цвета и характера освещения каждое пространство приобретает собственную атмосферу, а маршрут воспринимается как непрерывное погружение — от света поверхности к приглушённым глубинам подводного мира.'
  ];
  const hotspots=[[50,9],[52,31],[79,31],[79,50],[79,72],[52,72],[24,72],[24,50]];
  const rail=project.zones.map((zone,index)=>`<button class="museum-rail__item${index===0?' is-active':''}" type="button" data-museum-zone="${index}" aria-label="Показать зал: ${zone.title}" aria-pressed="${index===0}"><img src="${zone.image}" alt="" loading="${index<2?'eager':'lazy'}"><span><b>${String(index+1).padStart(2,'0')}</b>${zone.title}</span></button>`).join('');
  const planButtons=project.zones.map((zone,index)=>`<button class="museum-plan__marker${index===0?' is-active':''}" type="button" data-museum-zone="${index}" style="--x:${hotspots[index][0]}%;--y:${hotspots[index][1]}%" aria-label="${zone.title}" aria-pressed="${index===0}"><span>${index+1}</span></button>`).join('');
  document.querySelector('#content').innerHTML=`<article class="museum-case"><section class="museum-cover" aria-labelledby="museum-title"><img src="${project.image}" alt="${project.imageAlt}"><div class="museum-cover__shade"></div><div class="museum-cover__meta"><span>01 / дипломный проект / 2026</span><h1 id="museum-title">Музей о море</h1><p>Пространство погружения</p></div><a href="#museum-route" class="museum-cover__scroll">Исследовать маршрут <span>↓</span></a></section><section class="museum-explorer section" id="museum-route" aria-labelledby="museum-route-title"><div class="museum-explorer__head"><span>01—08 / состояния моря</span><h2 id="museum-route-title">Маршрут<br>погружения</h2><p>Наводите на точки плана или выбирайте кадры — изображение зала появится в центре.</p></div><div class="museum-explorer__layout"><nav class="museum-rail" aria-label="Визуализации залов">${rail}</nav><div class="museum-explorer__center"><figure class="museum-stage"><img src="${project.zones[0].image}" alt="${project.zones[0].alt}" data-museum-main><figcaption><span data-museum-count>01 / 08</span><strong data-museum-title>${project.zones[0].title}</strong><p data-museum-caption>${project.zones[0].description}</p></figcaption></figure><div class="museum-plan"><div class="museum-plan__label"><span>План экспозиции</span><span>Выберите зал</span></div><div class="museum-plan__drawing"><img src="../img/museum/plan.webp" alt="План помещений Музея о море">${planButtons}</div></div></div><aside class="museum-copy"><span>О проекте</span><p>${museumText[0]}</p><p>${museumText[1]}</p><dl><div><dt>Роль</dt><dd>Световая концепция и сценарий</dd></div><div><dt>Формат</dt><dd>Музейная экспозиция</dd></div><div><dt>Автор</dt><dd>Оксана Никитина</dd></div></dl></aside></div></section><a class="next-project" href="${project.next}"><span>Следующий проект<strong>${project.nextTitle}</strong></span><i>↗</i></a></article>`;

  document.querySelector('.museum-cover__meta p')?.remove();
  const mainImage=document.querySelector('[data-museum-main]');
  const count=document.querySelector('[data-museum-count]');
  const title=document.querySelector('[data-museum-title]');
  const caption=document.querySelector('[data-museum-caption]');
  const controls=[...document.querySelectorAll('[data-museum-zone]')];
  const railElement=document.querySelector('.museum-rail');
  const selectZone=(index,scrollRail=false)=>{
   const zone=project.zones[index];
   if(!zone||mainImage.dataset.zone===String(index)) return;
   mainImage.classList.add('is-changing');
   window.setTimeout(()=>{
    mainImage.src=zone.image;
    mainImage.alt=zone.alt;
    mainImage.dataset.zone=String(index);
    count.textContent=`${String(index+1).padStart(2,'0')} / ${String(project.zones.length).padStart(2,'0')}`;
    title.textContent=zone.title;
    caption.textContent=zone.description;
    mainImage.classList.remove('is-changing');
   },120);
   controls.forEach(control=>{
    const active=Number(control.dataset.museumZone)===index;
    control.classList.toggle('is-active',active);
    control.setAttribute('aria-pressed',String(active));
   });
   if(scrollRail){
    const activeRail=document.querySelector(`.museum-rail__item[data-museum-zone="${index}"]`);
    railElement?.scrollTo({top:activeRail.offsetTop-(railElement.clientHeight-activeRail.clientHeight)/2,behavior:'smooth'});
   }
  };
  mainImage.dataset.zone='0';
  controls.forEach(control=>{
   const index=Number(control.dataset.museumZone);
   control.addEventListener('mouseenter',()=>selectZone(index,control.classList.contains('museum-plan__marker')));
   control.addEventListener('focus',()=>selectZone(index,control.classList.contains('museum-plan__marker')));
   control.addEventListener('click',()=>selectZone(index,control.classList.contains('museum-plan__marker')));
  });
  return;
 }
 const cover=project.image?`<div class="project-cover"><img src="${project.image}" alt="${project.imageAlt||''}"></div>`:`<div class="project-cover project-cover--graphic" role="img" aria-label="Графическая заставка проекта"><span>${project.no}</span></div>`;
 const gallery=project.gallery?.length?`<div class="project-gallery">${project.gallery.map((src,index)=>`<figure><img src="${src}" alt="Материал проекта ${index+1}" loading="lazy"></figure>`).join('')}</div>`:'';
 const featuredWorks=project.featuredWorks?.length?`<section class="object-studies section">${project.featuredWorks.map(work=>`<article class="object-study"><div class="object-study__head"><span>${work.no}</span><h2>${work.title}</h2></div><div class="object-study__layout"><figure class="object-study__visual object-study__visual--${work.crop}"><img src="${work.image}" alt="${work.title}" loading="eager"></figure><div class="object-study__copy"><div><span>Идея</span><p>${work.idea}</p></div><div><span>Смысл</span><p>${work.meaning}</p></div><dl><dt>Материалы</dt><dd>${work.materials}</dd></dl></div></div></article>`).join('')}</section>`:'';
 const sidurCase=project.sidurCase?`<section class="sidur-case section"><div class="sidur-meaning"><span>Смысл</span><h2>Свет проявляет присутствие через тень</h2><div><p>Для выставки «Театр отсутствия» ключевыми становятся театральные тени от восковых скульптур, узкие световые пятна и разные цветовые температуры в зависимости от характера экспоната.</p><p>В экспозиции «Карта мифа» овальные световые пятна точно собирают внимание на произведениях. Свет не должен слепить зрителя и не превышает допустимый уровень освещённости для светочувствительных работ.</p></div></div><div class="sidur-section-head"><span>01 / эскизы</span><h2>Разработка<br>световых эффектов</h2></div><div class="sidur-sketch-grid">${project.sidurCase.sketches.map((src,index)=>`<figure><img src="${src}" alt="${index===0?'Чертёж пространства':'Эскиз световой концепции '+index}" loading="lazy"></figure>`).join('')}</div><div class="sidur-section-head"><span>02 / реализация</span><h2>Экспозиция</h2></div><div class="sidur-photo-grid">${project.sidurCase.photos.map((src,index)=>`<figure><img src="${src}" alt="Фотография экспозиции ${index+1}" loading="lazy"></figure>`).join('')}</div></section>`:'';
 const presentation=project.slides?.length?`<section class="project-presentation section"><div class="project-presentation__head"><span>Полная презентация / ${project.slides.length} слайдов</span><a href="${project.pdf}" target="_blank" rel="noopener">Открыть оригинал PDF ↗</a></div><div class="project-presentation__pages">${project.slides.map((src,index)=>`<figure><img src="${src}" alt="${project.slidesAlt||'Презентация'} — слайд ${index+1}" loading="${index?'lazy':'eager'}"></figure>`).join('')}</div></section>`:'';
 const documentSheet=project.documentImage?`<section class="project-document section"><div class="project-presentation__head"><span>${project.documentLabel}</span><a href="${project.pdf}" target="_blank" rel="noopener">Открыть оригинал PDF ↗</a></div><figure><img src="${project.documentImage}" alt="${project.documentAlt}" loading="eager"></figure></section>`:'';
 const pdfPresentation=project.pdfEmbed?`<section class="project-pdf section"><div class="project-presentation__head"><span>Полная презентация / 41 слайд</span><a href="${project.pdf}" target="_blank" rel="noopener">Открыть отдельно ↗</a></div><iframe src="${project.pdf}#view=FitH" title="Полная презентация проекта Кресты"></iframe></section>`:'';
 const nextAttrs=project.nextTarget?` target="${project.nextTarget}" rel="noopener"`:'';
 const story=`<section class="project-story section"><h2>О проекте</h2><div class="project-story__copy"><p>${project.lead}</p><p>${project.body}</p></div></section>`;
 const projectKey=document.body.dataset.project;
  const overview=projectKey==='theatre'?`<section class="theatre-overview">${story}${cover}</section>`:(projectKey==='clausura'||projectKey==='system-coordinates')?story:`${cover}${story}`;
 const cloudViewer=projectKey==='cloud'?`<section class="cloud-model section" aria-labelledby="cloud-model-title"><div class="cloud-model__head"><span>Интерактивная UX-модель</span><h2 id="cloud-model-title">Оптическая система</h2><p>Вращайте объект мышью или пальцем. Серебряные грани — зеркала на маршруте луча, прозрачные — стекло.</p></div><div class="cloud-viewer" data-cloud-viewer><canvas aria-label="Интерактивная трёхмерная модель инсталляции Облако"></canvas><div class="cloud-viewer__hud"><span>Зажмите и вращайте</span><button type="button" data-cloud-reset>Сбросить вид</button></div><div class="cloud-viewer__status" data-cloud-status>Загрузка модели…</div></div></section>`:'';
 document.querySelector('#content').innerHTML=`<section class="project-hero"><div class="project-hero__meta"><span>${project.no}</span><span>${project.type}</span><span>${project.year}</span></div><h1>${project.title}</h1><div class="project-hero__intro"><p>${project.lead}</p><dl><div><dt>Роль</dt><dd>${project.role}</dd></div><div><dt>Статус</dt><dd>${project.status}</dd></div><div><dt>Автор</dt><dd>${project.author||'Оксана Никитина'}</dd></div></dl></div></section>${overview}${cloudViewer}${featuredWorks}${sidurCase}${documentSheet}${pdfPresentation}${presentation}${gallery}<a class="next-project" href="${project.next}"${nextAttrs}><span>Следующий проект<strong>${project.nextTitle}</strong></span><i>↗</i></a>`;
}
})();
